# This action would be used in PR requests to build a single docker images

name: Build Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name for the Docker image'
        required: true
        type: string
      target_name:
        description: 'Target name if image used multi-stage build' # Specific to core-api
        required: false
        type: string
      image_tag:
        description: 'Tag for the Docker image (optional)'
        required: false
        type: string
        default: 'latest'

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to inspect all commits

      - name: Build Docker Image
        id: build-image
        run: |
          docker build -t ${{ inputs.image_name }}:${{ inputs.image_tag }} ${{ inputs.target_name }} .